### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ning-mi** [lixiangpengcs/CARE#1]
Could you offer your dataset and the usage of the code? Appreciate!

**Comment by lixiangpengcs** [comment]
Sorry, I adopt the Faster-RCNN features as region feature following MVAN: https://github.com/taesunwhang/MVAN-VisDial. The contextual feature is much large and it is about 50G. I plan to upload it onto BaiduyunDisk and I will notify you when it is done.

**Comment by ning-mi** [comment]
Got it. Thanks for your work!

**Comment by ning-mi** [comment]
Hi! Did you finish uploading the contextual feature? If the transmission rate is too slow, maybe you can try aliyunDisk.

**Comment by lixiangpengcs** [comment]
The contextual feature has been uploaded.
