### ISSUE TITLE
Dan_faster_rcnn

### ISSUE THREAD

**Issue by ning-mi** [lixiangpengcs/CARE#3]
Where can we find the dan_faster_rcnn? When i use the faster_rcnn, it throwred a error that is **KeyError: "Unable to open object (object 'image_features' doesn't exist)"**

**Comment by lixiangpengcs** [comment]
The feature we used is extracted by grid-feats-vqa: https://github.com/facebookresearch/grid-feats-vqa. But this feature is too big (about 200 G) to upload. You can extract it by yourself. The same faster-RCNN feature is also provided by https://github.com/taesunwhang/MVAN-VisDial. Their performances are almost the same. You can modify some dataset codes and replace them by yourself.

**Comment by ning-mi** [comment]
Hi, when i try to extract the grid region features using the [grid-feats-vqa](https://github.com/facebookresearch/grid-feats-vqa), i not find the code of extracting grid region whose backbone is x101? Would you mind provide me the code to extract the features? I'll be appreciate of it!

**Comment by ning-mi** [comment]
The %_simorder.pkl i can't find too, please tell me how to get it!
